// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nngcfhbrpyjauwwkcutb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZ2NmaGJycHlqYXV3d2tjdXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0NDA5ODksImV4cCI6MjA5OTAxNjk4OX0.tpXlGpVBKIimnZb3kKG4m3t2ax2h2D5Y3-Esgvm8p4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});